# Generated by Django 3.2.7 on 2021-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data',
        ),
        migrations.AddField(
            model_name='post',
            name='data_publi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
